### ISSUE TITLE
New function reqest

### ISSUE THREAD

**Issue by alvinlee418** [Looking-Glass/HypercubeCalibrator#1]
Hi, considering the double image thing, I have been using the mouse pointer to verify if a position gives double image or rainbow. This is quick and simple but not so reliable. After the calibration, we define the new boundary of each slices and I wonder if I can control a point, 1 pixel in size ideally, to scan through positions only within the new boundaries to verify the double image and rainbow problem. If that pointer gives its x-y position in pixel, it will be extra nice.

**Comment by Dezt** [comment]
Hey Alvin reopen this issue, if the unity GUI is not sufficient to meet this requirement.
